version: 2

models:
  - name: dim_accounts
    description: "Dimension table for customer accounts."
    columns:
      - name: account_id
        description: "Primary key for dim_accounts."
        tests:
          - not_null
          - unique

  - name: dim_titles
    description: "Dimension table for movie titles."
    columns:
      - name: title_id
        description: "Primary key for dim_titles."
        tests:
          - not_null
          - unique

  - name: dim_genres
    description: "Dimension table for movie genres."
    columns:
      - name: genre_name
        description: "Primary key for dim_genres."
        tests:
          - not_null
          - unique
